# -*- coding: utf-8 -*-
"""Assignment5updated.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DKtjtHof5OinGh3cmuvX78oAACoZCRWj
"""

import streamlit as st
import pandas as pd

# Title for the app
st.title("Welcome to Streamlit App")

# Ask for the user's name
name = st.text_input("Enter your name:")

# Display the name if it is provided
if name:
    st.write(f"Hello, {name}! Welcome to the app.")