# -*- coding: utf-8 -*-
"""Assignment5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DKtjtHof5OinGh3cmuvX78oAACoZCRWj
"""

# Asking for the user's name
user_name = input("Please enter your name: ")

# Displaying the name
print(f"Hello, {user_name}! Nice to meet you.")